// GapGuard news-aware backtest — same deterministic gap engine as backtest.ts,
// but the agent STANDS ASIDE on sessions whose cached gate verdict says the
// overnight move is justified repricing instead of blindly fading it.
//
// This is the deterministic, label-grounded view of GapGuard's core thesis: the
// edge is not fading every gap (that's ~flat) but judging which gaps are justified
// repricing and standing aside. The label-grounded catalyst variants remain as a
// baseline; the gate-driven variant consumes data/aaplusdt-gate-verdicts.json,
// generated by `npm run gate:audit` when BITGET_QWEN_API_KEY is available.
//
//   npm run backtest:news

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import type { Candle } from "./gapEngine";
import { loadGateVerdicts } from "./gateVerdicts";
import {
  buildNewsBacktestReport,
  type Catalyst,
} from "./newsBacktestReport";
import { resolveBacktestSlippage } from "./slippage";

const GAP_THRESHOLD = Number(process.env.BT_GAP_THRESHOLD ?? "0.004");
const COST_PER_SIDE = Number(process.env.BT_COST ?? "0.0005");
const START_EQUITY = 1000;

const candleFile = resolve(process.argv[2] ?? "data/aaplusdt-1h.json");
const catalystFile = resolve(process.argv[3] ?? "data/aaplusdt-catalysts.json");
const gateVerdictFile = resolve(
  process.argv[4] ??
    process.env.BT_GATE_VERDICTS ??
    "data/aaplusdt-gate-verdicts.json",
);
const fixture = JSON.parse(readFileSync(candleFile, "utf8")) as {
  symbol: string;
  granularity: string;
  candles: Candle[];
};
const catalystDoc = JSON.parse(readFileSync(catalystFile, "utf8")) as {
  catalysts: Catalyst[];
};
const { symbol, candles } = fixture;
const catalysts = catalystDoc.catalysts;
const slippage = resolveBacktestSlippage([symbol]);

const gateCache = existsSync(gateVerdictFile)
  ? loadGateVerdicts(gateVerdictFile)
  : null;
if (gateCache && gateCache.asset !== symbol) {
  throw new Error(
    `Gate verdict cache asset ${gateCache.asset} does not match candle asset ${symbol}`,
  );
}

const report = buildNewsBacktestReport({
  symbol,
  interval: fixture.granularity,
  candles,
  catalysts,
  gapThreshold: GAP_THRESHOLD,
  costPerSide: COST_PER_SIDE,
  slippageBps: slippage.slippageBps,
  slippageSource: slippage.source,
  startEquity: START_EQUITY,
  gateVerdictPath: gateVerdictFile,
  gateCache,
});

const out = resolve("artifacts/aaplusdt-news-aware-backtest.json");
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, `${JSON.stringify(report, null, 2)}\n`);

console.log(
  `\nGapGuard news-aware backtest — ${symbol} (${report.window.from} -> ${report.window.to})`,
);
const table: Record<string, { "return %": number; trades: number; "win %": number }> = {
  "always-fade (baseline)": {
    "return %": report.variants.alwaysFade.totalReturnPct,
    trades: report.variants.alwaysFade.totalTrades,
    "win %": report.variants.alwaysFade.winRatePct,
  },
};
if (report.variants.gateDriven) {
  table["gate-driven"] = {
    "return %": report.variants.gateDriven.totalReturnPct,
    trades: report.variants.gateDriven.totalTrades,
    "win %": report.variants.gateDriven.winRatePct,
  };
}
table["AAPL-label-aware"] = {
  "return %": report.variants.aaplNewsAware.totalReturnPct,
  trades: report.variants.aaplNewsAware.totalTrades,
  "win %": report.variants.aaplNewsAware.winRatePct,
};
table["all-label-aware"] = {
  "return %": report.variants.allCatalystAware.totalReturnPct,
  trades: report.variants.allCatalystAware.totalTrades,
  "win %": report.variants.allCatalystAware.winRatePct,
};
console.table(table);
if (!report.variants.gateDriven) {
  console.log(
    `  gate-driven: missing ${gateVerdictFile}; run gate:audit with BITGET_QWEN_API_KEY to generate it`,
  );
} else {
  console.log(
    "  stood aside (gate):",
    report.skippedOnCatalyst.gate
      .map((t) => `${t.date} ${t.returnPct > 0 ? "+" : ""}${t.returnPct}%`)
      .join(", ") || "none",
  );
}
console.log(
  "  stood aside (AAPL labels):",
  report.skippedOnCatalyst.aapl
    .map((t) => `${t.date} ${t.returnPct > 0 ? "+" : ""}${t.returnPct}%`)
    .join(", ") || "none",
);
console.log(`saved: ${out}`);
